### ISSUE TITLE
Create a DB table to feed into TensorFlow

### ISSUE THREAD

**Issue by alexgreene** [alexgreene/game-scout#1]
## TO DO:
Each row should be a game, one of the columns should categorize the game as 1-run game or not (1 = yes, 0 = no). The other columns are different data points about the game. Some ideas:

- [x] categorized as a 1-run game or not
- [x] run differentials for both teams
- [x] winning pct for each team
- [x] winning pct for each team in 1 run games
- [x] winning pct for each team in 2 run games
- [x] average runs scored/allowed in wins/losses
- [x] ERA for both pitchers
- [x] avg innings pitched per pitcher
- [x] w/l split between the two teams in current season
- [x] batting average for each position on that team in the last 10 games (1B, 2B, 3B, etc)
- [x] avg home runs per game for each team for the last 50 games

~~number of innings with 1 run scored for each team~~
~~difference in winning pct for the teams~~
~~difference in ERA for the two pitchers~~
~~difference in run differential~~
~~game_score averages for each pitcher on their last 3 starts~~

exponential weighted moving average

references:
http://www.hardballtimes.com/the-one-about-win-probability/
http://www.hardballtimes.com/ten-things-about-one-run-games/

**Comment by gtarantino** [comment]
## Completed:

• 1-run game 
• difference in winning pct for the teams
